- pkg/commands/deploy.go
> Deploy crd

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/setup.go
- pkg/deployer/deployer.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/images/consts.go
- pkg/kubeletconfig/kubectl.go
We add support to deploy a topology-updater component, which happens to be RTE for the time being.
> Add code do deploy RTE

- pkg/deployer/sched/sched.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/manifests/yaml/sched/namespace.yaml
a couple bugs prevent the deploy command to complete. Fix them.
> Fix deploy command

- test/e2e/positive.go
Do not assume we will always only have one worker.
> e2e: deploy: generalize the deploy test

- pkg/deployer/deployer.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/deployer/wait/wait.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
generalize the wait and abstract it
> refactor how we wait for objects to be created/deleted

- hack/rte.yaml
- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/rte/rte.go
- pkg/manifests/updates.go
- test/e2e/positive.go
> rte: add code to inject a configmap

- .github/workflows/release.yml
> Add a release lane

- .github/workflows/release.yml
The first attempt didn't really delivered the expected results,
so fix as needed.
> release: fixes to the release flow

- cmd/deployer/main.go
- go.mod
- pkg/clientutil/nodes/nodes.go
- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/commands/validate.go
- pkg/commands/version.go
- pkg/deployer/api/api.go
- pkg/deployer/deployer.go
- pkg/deployer/platform/detect/detect.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/deployer/wait/wait.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
- pkg/validator/kubeletconfig.go
- test/e2e/e2e_test.go
- test/e2e/positive.go
- test/e2e/utils/pods/pods.go
github.com/fromanirh/... -> github.com/k8stopologyawareschedwg/...
> project: fix project URL and import paths

- .github/workflows/go.yml
- Makefile
- pkg/kubeletconfig/kubectl.go
Add a target to run `go vet`, hook it up in the GH actions, and fix a bug exposed by `go vet`.
> add and use go vet

- pkg/commands/render.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/rte/rte.go
- pkg/manifests/rte/rte_test.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
- pkg/manifests/updates_test.go
- pkg/manifests/yaml/rte/daemonset.yaml
- test/e2e/positive.go
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Set static parameters during manifests load instead of updating it after

- pkg/manifests/manifests_test.go
- pkg/manifests/rte/rte.go
- pkg/manifests/yaml/rte/clusterrole.yaml
- pkg/manifests/yaml/rte/clusterrolebinding.yaml
- pkg/manifests/yaml/rte/role.yaml
- grant NRT permissions on the cluster scope level
- grant permissions to update pod conditions under the RTE daemon set
namespace
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> rte: fix permissions issues related to latest RTE changes

- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
Adding the notifier file will not harm under Kubernetes platform
and will make testing easier.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Always add notify file for both OpenShift and Kubernetes platform

- pkg/commands/render.go
- pkg/deployer/rte/rte.go
> Create ns for RTE on all platforms

- README.troubleshooting.md
> doc: start troubleshooting docs

- hack/make-checksum.sh
catch up with the renaming changes
> hack: fix make-checksum

- .github/workflows/e2e.yml
- .github/workflows/release.yml
grab bag of fixes for the gh actions workflows
> Fix gh actions

- test/e2e/positive.go
- test/e2e/utils/wait/deployment.go
add a e2e test to check the scheduler plugin - and only the
scheduler plugin (+ API otherwise we know it will go in crashloop)
fixes #93 
> e2e: initial partial deployment test

- .github/workflows/e2e.yml
- .github/workflows/go.yml
let's save minutes post-merge.
> gh actions: don't run e2e on push

- .github/workflows/e2e.yml
- .github/workflows/go.yml
based on
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
> gh actions: update manifest

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
We don't set the Z value, meaning "pull the latest from the Y stream". We will need to check this is actually the semantics we get.
> golang: update to 1.19

- pkg/commands/setup.go
- pkg/commands/validate.go
- pkg/deployer/api/api.go
fix occurrences of misplaced/missing/wrongly labeled logs.
> pkg: log: fix misplaced logs

- pkg/manifests/updates.go
Split the scheduler config update logic proper
from the logic which updates the config map.
This makes the code more reusable.
> manifests: split render from update

- go.mod
- go.sum
- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/manifests/manifests.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/objectupdate/nfd/nfd.go
- pkg/objectupdate/nfd/nfd_test.go
- pkg/objectupdate/rte/rte.go
- test/e2e/e2e_test.go
- test/e2e/negative.go
- test/e2e/positive.go
- vendor/github.com/OneOfOne/xxhash/.gitignore
- vendor/github.com/OneOfOne/xxhash/.travis.yml
- vendor/github.com/OneOfOne/xxhash/LICENSE
- vendor/github.com/OneOfOne/xxhash/README.md
- vendor/github.com/OneOfOne/xxhash/xxhash.go
- vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
- vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
- vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
- vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/attribute/attribute.go
- vendor/github.com/k8stopologyawareschedwg/podfingerprint/LICENSE
- vendor/github.com/k8stopologyawareschedwg/podfingerprint/README.md
- vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go
- vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go
- vendor/modules.txt
instead of hardcoding PFP settings just for RTE,
add a top-level option to toggle the value for both supported updaters.
We default to enabled because this is what both RTE and NFD suggests (mostly RTE actually).
Fixes: https://github.com/k8stopologyawareschedwg/deployer/issues/153
> updater: add top-level option to toggle PFP support

- test/e2e/e2e_test.go
> Cleanup 20230318

- pkg/assets/rte/selinuxpolicy/ocp_v4.11.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.12.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.13.cil
catch up with container-selinux v2.188 and 2.199
> [release-0.12] update ocp policies

- pkg/assets/rte/selinuxpolicy/ocp_v4.11.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.12.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.13.cil
catch up with container-selinux v2.188 and 2.199
> [release-0.10] update ocp policies

- hack/setup-minikube.sh
- pkg/images/consts.go
Add recipe to create a meaningful minimal env to try out the topology aware scheduling.
The caveat is however you will need a powerful machine to run the env.
> add minikube setup recipe

- hack/setup-minikube.sh
- pkg/images/consts.go
Add recipe to create a meaningful minimal env to try out the topology aware scheduling.
The caveat is however you will need a powerful machine to run the env.
> [release-0.12][manual] add minikube setup recipe

- hack/setup-minikube.sh
fix:
- permissions
- typo in heredoc
- output about next steps
> hack: fix setup-minikube.sh

- hack/setup-minikube.sh
instead of adding command line options, which are
deprecated and just can't work for memory manager, let's do it differently:
- create a kubeletconfiguration "patch" (very crude, but works) which is also pretty stable. Note we assume the merge works right because the defaults are not specified.
- create helper scripts to merge the config, remove the stale state, restart the kubeket
- use all the above to fix (only) the worker nodes
more complex, but it gets us where we need to be.
TODO: find a more robust way to merge the yaml.
> hack: minikube: use config patch

- pkg/kubeletconfig/configz.go
- pkg/kubeletconfig/configz_test.go
- pkg/kubeletconfig/kubectl_test.go
trivial cleanup to the kubeletconfig package and most notably initial test coverage
> Kubeletconfig: cleanup, add tests

- pkg/deployer/platform/detect/detect.go
- pkg/deployer/platform/detect/detect_test.go
Refactor the code to enable easier unit testing, and kickoff the unit tests.
No expected changes in behavior.
> pkg: platform: detect: kickoff unit tests

- pkg/images/consts.go
> deps: bump RTE to 0.14.2

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> golang: toolchain: bump to 1.20

- .github/workflows/e2e.yml
- .github/workflows/release.yml
> ghactions: workflow: bump to kind 1.27.3

- pkg/commands/root.go
> defaults: enable scheduler cache by default

- .github/workflows/go.yml
these tests are cheap, let's do them.
> gh actions: run unit tests on all branches

- .github/workflows/go.yml
these tests are cheap, let's do them.
> [release-0.15] gh actions: run unit tests on all branches

- .github/workflows/go.yml
these tests are cheap, let's do them.
> [release-0.14] gh actions: run unit tests on all branches

- .github/workflows/go.yml
these tests are cheap, let's do them.
> [release-0.13] gh actions: run unit tests on all branches

- .github/workflows/e2e.yml
- .github/workflows/release.yml
bump ubuntu imate to 22.04
bump kind cluster image to 1.25.z latest
> [release-0.13] gh actions: update config

- pkg/deployer/wait/crd.go
- pkg/deployer/wait/daemonset.go
- pkg/deployer/wait/deployment.go
- pkg/deployer/wait/wait.go
- pkg/kubeletconfig/configz.go
- pkg/manifests/schedparams.go
- pkg/objectupdate/sched/render.go
> [release-0.16][manual] cleanups: fix linter issues 20231026

- pkg/kubeletconfig/configz.go
- pkg/manifests/schedparams.go
- pkg/objectupdate/sched/render.go
> [release-0.15][manual] cleanups: fix linter issues 20231026 

- pkg/kubeletconfig/configz.go
- pkg/manifests/schedparams.go
- pkg/objectupdate/sched/render.go
> [release-0.14][manual] cleanups: fix linter issues 20231026

- pkg/kubeletconfig/configz.go
- pkg/manifests/schedparams.go
- pkg/objectupdate/sched/render.go
> [release-0.13][manual] cleanups: fix linter issues 20231026

- doc/examples/pod.burst.yaml
> doc: examples: add pod burst manifest

- pkg/flagcodec/flagcodec.go
- pkg/flagcodec/flagcodec_test.go
Following the conventions outlined in RATIONALE.md, the pflag packages allows using both `--v` and `-v` (double or single dashes for single-letter flags), but the flagcodec package  wasn't behaving the same, treating the two flags as different.
We add options to conform to our own rationale and to be more compatible with pflag.
> pkg: flagcodec: enable flag normalization

- pkg/assets/selinux/assets.go
misnamed constant issue sneaked in
> [release-0.18] assets: fix backport bug

- pkg/assets/selinux/assets.go
- pkg/assets/selinux/assets_test.go
- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/assets/selinux/policy/ocp_v4.15.cil
catch up and backport fixes committed to the release 0.18.z
> [release-0.17][manual] selinux policy updates for 4.14 and 4.15

- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/commands/render.go
backport: minimize the policies and new render policy subcommand
> [release-0.18] selinux cleanups

- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/assets/selinux/policy/ocp_v4.15.cil
- pkg/commands/render.go
backport: minimize the policies and new render policy subcommand
>  [release-0.17] selinux cleanups

- README.md
catch up with modern deployer versions
Fixes #256
> doc: update the compatibility matrix

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
v3 are deprecated, so we bump to v4
> ghactions: bump actions

- pkg/commands/render.go
- pkg/commands/root.go
- pkg/manifests/sched/sched.go
- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
- pkg/options/options.go
previously we missed this support for no good reason, let's fill this gap.
Fixes: #267
> sched: add support for setting the ScoringStrategy

- README.md
- pkg/images/consts.go
bump all refs to the latest stable releases
> deps: images: bump all refs

- pkg/commands/deploy.go
- pkg/commands/remove.go
- pkg/commands/render.go
- pkg/deploy/cluster.go
We need to pass the data in all the flows,
not just on the render flow.
> commands: sched: pass through scoringStrategy config

- pkg/manifests/sched/sched.go
- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
add support to get/set LeaderEletion parameters programmatically.
>  manifests: sched: support for LeaderElection params

- pkg/manifests/sched/sched.go
- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
add support to get/set LeaderEletion parameters programmatically.
manual cherry-pick of #299
> [release-0.19] manifests: sched: support for LeaderElection params

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
build using golang 1.22.5, latest at time of writing
> ghactions: golang: bump to 1.22

- pkg/commands/deploy.go
- pkg/commands/remove.go
- pkg/deploy/cluster.go
- pkg/deployer/platform/detect/detect.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
There were few places where we forgot to pass the `UpdaterCustomSELinuxPolicy` option. This commit is suppose to fix that.
> deployer: pass `UpdaterCustomSELinuxPolicy`

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
consume latest fixes and fix nodejs compatibility
> gh actions: bump github actions

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
consume latest fixes and fix nodejs compatibility
> [release-0.20][manual] gh actions: bump github actions

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
bump golang build toolchain to 1.23
> Bump golang build 1.23

- test/e2e/e2e_test.go
- test/e2e/positive.go
- test/e2e/utils/dump/dump.go
dump (try to) more data on error to help troubleshoot CI failures.
> [release-0.19] e2e: more troubleshoot utilities

- test/e2e/e2e_test.go
- test/e2e/positive.go
- test/e2e/utils/dump/dump.go
dump (try to) more data on error to help troubleshoot CI failures.
> e2e: more troubleshoot utilities

- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/assets/selinux/policy/ocp_v4.17.cil
This reverts commit 12718ed5c8ea8647588b28104c371a0096759663.
(cherry picked from commit 86701b3fe2630443240423ff59ed39c71e800ac4)
> [release-v0.21][manual] Revert "selinux: add kubelet_var_lib_t permissions"

- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/assets/selinux/policy/ocp_v4.17.cil
This reverts commit 12718ed5c8ea8647588b28104c371a0096759663.
(cherry picked from commit 86701b3fe2630443240423ff59ed39c71e800ac4)
> [release-v0.20][manual] Revert "selinux: add kubelet_var_lib_t permissions"

- pkg/assets/selinux/policy/ocp_v4.16.cil
This reverts commit 12718ed5c8ea8647588b28104c371a0096759663.
(cherry picked from commit 86701b3fe2630443240423ff59ed39c71e800ac4)
> [release-v0.19][manual] Revert "selinux: add kubelet_var_lib_t permissions"

- pkg/commands/root.go
- pkg/manifests/rte/rte.go
- pkg/options/options.go
> [release-0.21][manual] manifests: selinux: openshift add v2 SCC

- pkg/images/consts.go
The current image is outdated and should be updated.
> update RTE image reference
