k8stopologyawareschedwg/deployer

- pkg/manifests/yaml/rte/namespace.yaml
- pkg/manifests/yaml/sched/namespace.yaml
Add a `tas-` prefix and make the namespace name more
descriptive.
> manifests: make namespace names uniform

- pkg/commands/deploy.go
- pkg/commands/root.go
- pkg/commands/validate.go
- pkg/deployer/api/api.go
- pkg/deployer/deployer.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
We need only two level of logging
- regular status messages
- debug messages (for troubleshooting)
So we build a minimal abstraction on top of the stdlib's `log`
package.
It's important to keep the distinction between logging and output.
The former is about status messages, which are useful to track
the program flow, and which are most used to track progress or
to understand what went wrong.
The latter is about the expected output from a program.
In our case:
- deploy/remove has logging, not output.
- render has output, may have logging (in the future)
- validate has logging and output
We should never mix logging and output on the same destination
(e.g on stdout)
> pkg: revamp logging

- pkg/manifests/yaml/sched/clusterrolebinding-vol-sched.yaml
- pkg/manifests/yaml/sched/deployment.yaml
Fix minor mistakes that found their way in the scheduler plugin manifests, and align to how the default kube scheduler behaves.
> Fix the scheduler plugin manifests

- pkg/commands/deploy.go
- pkg/deployer/deployer.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- test/e2e/positive.go
Add flag to wait for deployment/daemonset to be fully
running and ready before to return.
Same goes for the remove flow, which now tries
to remove as much as possible instead of bail out at
the first error.
> pkg: add optional wait for resources

- pkg/images/images.go
- test/e2e/positive.go
Add env variables to be able to override images without
recompiling. This is meant to be a very sporadic action,
so we kept the option half-hidden using env variables.
Should this turn to be more used than we anticipate, we will
revisit and promote to full blown options.
> images: add a way to override the image

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/api/api.go
- pkg/deployer/platform/platform.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- test/e2e/positive.go
Much like we already do with `deploy` and `remove` subcommands, we add support to only partially render the manifests.
> Render subcommands

- pkg/commands/render.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
- pkg/manifests/yaml/rte/daemonset.yaml
- test/e2e/positive.go
OCP add quite some layers of infrastructure.
In this patch we integrate RTE as much as possible
in the existing monitoring infrastructure.
> topology-updater: add support to deploy on OCP

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
Switch the default pull policy to `Always`, which is the best practice.
Add an option to set the pull policy as `IfNotPresent` which is still more practical in some cases, most notably in most CI environments
> manifest: add option to force the pull policy

- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/render.go
- pkg/commands/root.go
- test/e2e/positive.go
Previously, the code was overeager to autodetect the platform,
leading to potentially confusing behaviour (e.g. wrong help text)
and in general requiring KUBECONFIG excessively.
Move later in the flows which actually need it the platform detection.
> platform: detect: run detection only if needed

- pkg/commands/images.go
- pkg/commands/root.go
- test/e2e/e2e_test.go
- test/e2e/positive.go
This works as living documentation and makes
it trivial to find which images are going to
be used by the tool.
> command: add command to introspect the images

- pkg/images/consts.go
consume fixed image with shipped pciutils and pcidb.
> rte: bump to v0.0.20

- .github/workflows/go.yml
- hack/check-format.sh
- pkg/deployer/platform/detect/detect.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- test/e2e/utils/pods/pods.go
- test/log/log.go
resync the tree to make it compliant with gofmt standard, and add an automated check to ensure we keep the codebase clean.
> add gofmt to the build gh action

- pkg/commands/render.go
- pkg/deployer/api/api.go
- pkg/deployer/deployer.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/deployer/wait/wait.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- test/e2e/positive.go
Make the namespace setup explicit in the deployment steps. We intentionally keep a consistent API for now, even for modules on which setup namespace doesn't make sense, because the component is (and will always be) cluster-scoped (API) or because we need separate namespaces in any case (scheduler).
The main benefit of this change is that we perform a quite deep cleanup and streamlining in the RTE flow, and we handle in a bit friedlier its API.
In general, in the kubernetes flow we should always setup a separate namespace, but there are noteworthy cases (operators) on which the namespace setup should be handled on a different explicit step, and with this PR we can now handle those cases in a simpler way.
> rte: support to deploy on existing namespace

- pkg/manifests/updates.go
- pkg/manifests/updates_test.go
Consecutive calls for Manifests.Update() will append the same arg into the DaemonSet.Spec.Template.Spec.Containers[x].Command multiple time.
When we'll try to deploy the DaemonSet pods` the pod will failed because of this redundant args in the Command field.
In the usual case of running the deployer binary once and exit, this bug won't reproduce.
But on the numaresource-operator, we're calling the Manifests.Update() function multiple times and this is where the bug occoured.
> Fix DaemonSet update command

- pkg/manifests/rte/rte_test.go
These unit-tests are making sure that:
1. Clone creates a separate Manifests copy.
2. Update returns a separate Manifests copy and not changing the original one.
> Add unit-tests for Clone and Update

- pkg/manifests/updates.go
- pkg/manifests/updates_test.go
- pkg/manifests/yaml/rte/daemonset.yaml
The deployer is not updating the DaemonSet with the necessary configuration for support metrics exports
as we have in the RTE repo: https://github.com/k8stopologyawareschedwg/resource-topology-exporter/blob/master/manifests/resource-topology-exporter-ds.yaml#L42
> Add missing logic for updating metrics port

- go.mod
- vendor/modules.txt
Although this version being replaced, for some reason it still interfer when other components are trying to consume the deployer.
Changed the version into a valid one.
> Valid version in go.mod's require field

- pkg/images/consts.go
These images will fix the panic caused by the wrong (missing) version.
> images: bump last scheduler plugin builds

- pkg/manifests/yaml/sched/scheduler/clusterrole.yaml
Add missing (intentionally RO) permissions to storage.k8s.io resources.
Looks like the core scheduler needs to watch these resources, and if it fails to watch them the scheduler doesn't initializes itself
correctly.
TL;DR: with the extra permissions, the scheduling works as expected;
without, it doesn't: pod requesting the secondary scheduler keep being Pending, even though NRT objects are populated correctly.
> sched: clusterrole: add missing permissions

- pkg/manifests/rte/rte.go
- pkg/manifests/updates.go
- pkg/manifests/updates_test.go
Expose functions to create and inject the RTE config map, to make it easier for external project to consume the deployer codebase.
> Expose config map functions

- pkg/manifests/rte/rte.go
- pkg/manifests/updates.go
We're creating the ConfigMap object with a name which is based on the DaemonSet's name,
but when we're mounting the ConfigMap as a volume we're using a constant name which is not the real ConfigMap's name.
The result is that the pod is getting deployed without a mounted ConfigMap.
> Mount configmap with the correct name

- pkg/manifests/sched/sched.go
The rolebinding deployed at the kube-system ns and not in the scheduler ns, thus we need to delete it explicitly
> Delete scheduler rolebinding resource

- pkg/manifests/yaml/rte/daemonset.yaml
This patch will allow RTE to use the podreadiness feature while we deploy it using the deployer/numaresource-operator
> Add podreadiness under daemonset

- pkg/commands/render.go
- pkg/deployer/rte/rte.go
- pkg/deployer/sched/sched.go
- pkg/manifests/api/api.go
- pkg/manifests/rte/rte.go
- pkg/manifests/rte/rte_test.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
- test/e2e/positive.go
We had the unfortunate choice of name of "update" which was misleading and wrong. The intent of the code was to render manifests, not to update them. Fix the API accordingly.
> cleanup: rename the misleading "update" api

- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/yaml/rte/daemonset.yaml
Per the documentation:
```
When you create a Pod, you can define a command and arguments for the containers that run in the Pod.
To define a command, include the `command` field in the configuration file. To define arguments for
the command, include the `args` field in the configuration file.
The command and arguments that you define cannot be changed after the Pod is created.
```
(see:
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
see also:
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes)
The most correct and precise form is thus to supply *both* `command` and
`args` - and that was the original intent of the manifest; conveying
everything into the `command` is a slightly abuse, even if this …
> manifests: rte: split args from command

- README.md
Add sections to explain the rationale and the goals for the deployer
tool. Take the chance to mention and introduce the `render` command.
> doc: README: explain render mode and rationale

- .github/workflows/release.yml
- Makefile
- hack/make-checksum.sh
Use the `deployer` binary built as release artifact to generate (and add to released artifact) the manifests.
This enables users interested only in released manifests to download them right away, instead of being force to download the deployer binary first.
Closes: https://github.com/k8stopologyawareschedwg/deployer/issues/81
> release: render manifests using deployer

- .github/workflows/release.yml
Render manifests earlier in the flow, and
actually include them in the release payload.
> gh actions: release: actually ship manifests

- .github/workflows/release.yml
This will also prevent the manifests to be exported
twice as release artifacts.
> gh actions: make manifests name consistent with binary

- pkg/manifests/codec.go
- pkg/manifests/manifests.go
Let's remove fields which doesn't make sense
as render target, because they are managed by the cluster
and thus are ignored anyway when we submit the manifests,
like status and creationTimestamps.
> pkg: manifests: cleanup useless fields

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/images/consts.go
- pkg/images/consts_test.go
- pkg/images/images.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/nfd/nfd_test.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/manifests/updates.go
- pkg/manifests/updates_test.go
- pkg/manifests/yaml/nfd/master/clusterrole.yaml
- pkg/manifests/yaml/nfd/master/clusterrolebinding.yaml
- pkg/manifests/yaml/nfd/master/deployment.yaml
- pkg/manifests/yaml/nfd/master/service.yaml
- pkg/manifests/yaml/nfd/master/serviceaccount.yaml
- pkg/manifests/yaml/nfd/namespace.yaml
- pkg/manifests/yaml/nfd/topologyupdater/clusterrole.yaml
- pkg/manifests/yaml/nfd/topologyupdater/clusterrolebinding.yaml
- pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
- pkg/manifests/yaml/nfd/topologyupdater/machineconfig.yaml
- pkg/manifests/yaml/nfd/topologyupdater/securitycontextconstraint.yaml
- pkg/manifests/yaml/nfd/topologyupdater/serviceaccount.yaml
- test/e2e/positive.go
This change will allow deployer to deploy NFD as the topology-updater component.
NFD is the u/s version of RTE, thus it's is important to have the ability to use it.
The default topology-updater component is still RTE since it's more mature and tested for quite some time.
This PR provides NFD support only for K8S.
We'll add support for OCP in the future when NFD will catch up with RTE (from abilities perspective)
> Deploy NFD as topology-updater component

- test/e2e/positive.go
Currently we have tests which do the overall deployment AND
perform the minimal validation on top of it.
Due to lack of CI resources, we always skip the validation, but
this also incorrectly marks the deployment as skipped.
Let's split the tests to get a better signal; while the
validation is expected to keep skipping, we can get a better
understanding from the deployment test.
> e2e: split deployment + validation test

- pkg/assets/rte/rte-notifier.sh
Use absolute path for jq. Even though `/usr/bin/jq` is not always
guaranteed to be correct, it is still better than depending on $PATH
when running as OCI hook.
Plus, in the most common container OSes, the jq path _is_ actually
/usr.bin/jq. Point in case, this is especially true for OCP, the only
platform on which we deploy and recommend this hook anyway.
> assets: notifier: use absolute path

- pkg/commands/deploy.go
- pkg/commands/images.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/commands/setup.go
- test/e2e/negative.go
The original intent of the `commands` pkg was to be reusable, to enable clients to inject deployer commands in their own programs. This turns out harder than expected in practice, because of somehow excessive coupling in the `commands` pkg.
This PR relaxes these contraints and make sure that these commands, at least the `render` subtree, is actually reusable in external projects.
> pkg: commands: refactor commands to make them reusable

- pkg/commands/detect.go
- pkg/commands/root.go
- pkg/deployer/platform/detect/detect.go
- pkg/deployer/platform/platform.go
- pkg/deployer/platform/version.go
- test/e2e/e2e_test.go
- test/e2e/positive.go
We will soon need to support version-specific configuration (e.g. in MachineConfig).
To enable this, we add the concept of platform version (retroactively renaming the current platform as "kind") all across the stack.
This is a API-breaking enablement PR only: consumers of this new data will be added in future PRs.
> pkg: detect cluster version alongside platform

- pkg/images/consts.go
Previously, we just neglected to update the builtin images, trusting the user to replace them. Time to fix the defaults
to something more modern than ancient 0.3.1, but still compatible with the NRT API 0.0.12.
The scheduler side will be updated with a different PR.
> images: RTE: bump to v0.6.0

- Makefile
we now require explicitly the platform AND the version,
let's fix the Makefile target - and then the release flow.
> Makefile: catchup with -P changes

- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/deployer/platform/detect/autoselection.go
When the package autoselects the version, it can try to autodetect
from cluster. This is a desired behaviour, but autodetection
can raise an error, and we should properly bubble the error up.
> platform: expose error on autodetection

- pkg/manifests/yaml/rte/clusterrole.yaml
We want to keep the manifests in sync with RTE.
This is needed due to recent changes introduced at:https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/120
> rte:rbac: update rbac permissions

- pkg/manifests/codec.go
- pkg/manifests/manifests.go
Serializing/Deserializing is useful for client applications when deal with scheduler plugin arguments.
> manifests: expose codec functions

- pkg/commands/images.go
Previously, we mistakenly ignored the flag in the
`images` subcommand, for no good reason. Time to fix.
> pkg: images: honor --updater-type

- pkg/commands/deploy.go
- pkg/commands/root.go
- pkg/deployer/api/api.go
- pkg/deployer/deployer.go
- pkg/deployer/sched/sched.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/deployer/wait/wait.go
- pkg/manifests/api/api.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
remove the Helper abstraction. Seemed a good idea, turned out to lack focus and adding unnecessary abstraction.
We turn the good bits of Helper into a plain Data-only object we use to pass around the context. Some methods are too shallow and are just inlined; other are copied (and made private) in the one and only calling site.
Closes: #113
> pkg: deployer: dissolve Helper

- pkg/clientutil/nodes/nodes.go
- pkg/commands/deploy.go
- pkg/commands/root.go
- pkg/commands/validate.go
- test/e2e/positive.go
Aiming to maximize the reuse of clients, we now require a `deployer.Environment` in the `nodes` subpkg.
This decision is not straightforward, as we have now a kinda clumsy dependency between `deployer` and `clientutil/nodes`. Since `nodes` is a subpkg, the pros seems to outweight the cons, but this decision can be revisited in the future.
Surely, one way or another, `clientutil/nodes` should reuse context, logger and client (= the Env, in some shape or form).
> pkg: clientutil: commands: use env in `nodes`

- pkg/images/consts.go
trivial image bump, no API changes are expected.
> images: bump RTE to v0.9.0

- .github/workflows/release.yml
- hack/make-checksum.sh
simplification of the release flow. This includes compressing the steps - we don't need multi stage builds but also compressing the output binary, which saves roughly 50% of the overall artifacts size.
> release flow: simplify and compress

- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/root.go
- pkg/deployer/deployer.go
- pkg/deployer/platform/detect/autoselection.go
- pkg/deployer/platform/detect/detect.go
- pkg/deployer/sched/sched.go
- pkg/deployer/updaters/updaters.go
- pkg/deployer/wait/daemonset.go
- pkg/deployer/wait/deployment.go
- pkg/deployer/wait/wait.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- test/e2e/positive.go
Up until now, the project libraries hardcoded `context.TODO()` instead of requiring a context from the caller.
This is a bad practice and makes impossible to cancel the APIs, even when the underlyingl libraries allowed to in turn accepting a context.
Fix the API to accept contexts, and pass them through as needed.
> context: add and use explicit context in libraries

- go.mod
- go.sum
- pkg/deployer/updaters/updaters.go
- pkg/deployer/wait/daemonset.go
- pkg/deployer/wait/deployment.go
- pkg/deployer/wait/wait.go
- pkg/deployer/wait/wait_test.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- test/e2e/positive.go
- vendor/github.com/evanphx/json-patch/.gitignore
- vendor/github.com/evanphx/json-patch/LICENSE
- vendor/github.com/evanphx/json-patch/README.md
- vendor/github.com/evanphx/json-patch/errors.go
- vendor/github.com/evanphx/json-patch/merge.go
- vendor/github.com/evanphx/json-patch/patch.go
- vendor/github.com/go-logr/logr/testr/testr.go
- vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
- vendor/k8s.io/client-go/testing/interface.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
The functions in the wait package accumulated a large set of arguments. By introducing the Waiter object, created with the With() helper and reorganizing the way we pass arguments, we can have nicer APIs with actually less code passed around.
Example:
from:
```
_, err := wait.ForDeploymentComplete(ctx, cli, log, mf.DPController, wait.DefaultPollInterval, wait.DefaultPollTimeout)
```
to:
```
_, err := wait.With(cli, log).ForDeploymentComplete(ctx, mf.DPController)
```
Note Waiter is initialized with default values, wich can be changed using the Timeout() and Interval() helper using a fluent API.
Example:
```
_, err := wait.With(cli, log).Timeout(1*time.Minute).Interval(10*time.Second).ForDeploymentComplete(ctx, mf.DPController)
```
> wait: api: introduce the With() helper

- pkg/commands/deploy.go
- pkg/deployer/sched/sched.go
- pkg/manifests/manifests.go
grab bag of fixes meant to enable the shceduler plugin reserve cache: inconditionally enable the pods-fingerprinting RTE support (until https://github.com/k8stopologyawareschedwg/deployer/issues/153 is fixed). Properly pass through the stack the user setting, otherwise the option has no effect.
> enable pods fingerprint consumption

- README.md
For documentation purposes, because it's the very job of the toolkit tho ship a compatible stack - and to make it discoverable.
Fixes: #67
> doc: add compatibility matrix

- pkg/assets/rte/selinuxpolicy/ocp_v4.11.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.12.cil
- pkg/assets/rte/selinuxpolicy/ocp_v4.13.cil
catch up with container-selinux v2.188 and 2.199
> [release-0.11] update ocp policies

- hack/setup-minikube.sh
fix:
- permissions
- typo in heredoc
- output about next steps
> [release-0.12][manual] hack: fix setup-minikube.sh

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/flagcodec/flagcodec.go
- pkg/flagcodec/flagcodec_test.go
- pkg/manifests/manifests.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/objectupdate/nfd/nfd.go
- pkg/objectupdate/nfd/nfd_test.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/types.go
Instead of having per-layer struct, which leads to a lot of copying and most notably unnecessary complexity, define
generic cross-layer options struct and use them pervasively. 
Up until now the duplication proven to be cumbersome, for a change.
We will re-evaluate and inline later when/if there are clear benefits.
Along the way, use flagcodec to more robust argument processing when updating DaemonSets.
> introduce objectupdate common structs to reduce layers

- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
the manifests package should perform only minimal mutation, and only if/where needed.
RTE daemonset was an exception for legacy reasons, not by deliberate design. At long last, move mutations (and their tests) in the objectupdate/rte package.
> manifests: push all mutations on objectupdate

- pkg/commands/root.go
- pkg/objectupdate/nfd/nfd.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/types.go
Add top-level option to control the updaters verbosity Support for scheduler verbosity is planned for later series.
Fixes #175
> updaters: add option to control verbosity

- pkg/objectupdate/rte/rte.go
We need to always mount the kubelet config volume
on kubernetes, even if notification is disabled.
Notification enablement should only control the RTE option.
> rte: always mount kubelet config

- pkg/objectupdate/rte/rte.go
We need to always mount the kubelet config volume
on kubernetes, even if notification is disabled.
Notification enablement should only control the RTE option.
> [release-0.13][manual] rte: always mount kubelet config

- pkg/commands/deploy.go
- pkg/commands/images.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/images/images.go
- pkg/images/output.go
- pkg/images/output_test.go
- pkg/manifests/codec.go
- pkg/manifests/sched/sched.go
- pkg/manifests/sched/sched_test.go
another grab-bag of minor fixes to cleanup the latest wave of PRs.
> Cleanup 20230410

- hack/setup-minikube.sh
clarify and add missing recommendations about setting up the env.
> hack: minikube: fixups and docs

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/rte/rte.go
- pkg/manifests/rte/rte_test.go
- test/e2e/negative.go
- test/e2e/positive.go
The CRI hooks are unconditionally deployed, but that creates waste when the event-based notification mechanism is not enabled. We should expose a way to enable the callers to disable the deployment of CRI hooks to avoid unnecessary churn.
> updaters: add toggle to deploy CRI hooks

- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/sched/sched.go
- pkg/manifests/sched/sched.go
- pkg/objectupdate/sched/sched.go
- pkg/objectupdate/sched/sched_test.go
- test/e2e/positive.go
Add top-level option to control the scheduler verbosity. Note: the auxiliary scheduler controller is left out for now.
Fixes #189
> scheduler: add option to control verbosity

- .github/workflows/e2e.yml
- go.mod
- pkg/commands/deploy.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/sched/sched.go
- pkg/manifests/sched/sched.go
- pkg/objectupdate/affinity.go
- pkg/objectupdate/affinity_test.go
- pkg/objectupdate/sched/sched.go
- pkg/objectupdate/sched/sched_test.go
- test/e2e/e2e_test.go
- test/e2e/positive.go
- test/e2e/utils/pods/events.go
- test/e2e/utils/pods/pods.go
the scheduler is a control plane component, thus it should run by default on the control plane.
Fixes: #177
> sched: manifests: run on the control plane

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
Let's update to the latest LTS from the ancient 20.04, and also let's take the chance to pin the version explicitely rather than rely to floating tags.
> ghactions: pin images to ubuntu 22.04

- pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
- pkg/manifests/yaml/rte/daemonset.yaml
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
Quoting kube docs:
```
when accessing the `/var/lib/kubelet/pod-resources/kubelet.sock` from DaemonSet
or any other app deployed as a container on the host, which is mounting socket as
a volume, it is a good practice to mount directory `/var/lib/kubelet/pod-resources/`
instead of the `/var/lib/kubelet/pod-resources/kubelet.sock`. This will ensure
that after kubelet restart, container will be able to re-connect to this socket.
Container mounts are managed by inode referencing the socket or directory,
depending on what was mounted. When kubelet restarts, socket is deleted
and a new socket is created, while directory stays untouched.
So the original inode for the socket become unusable. Inode to directory
will continue working.
```
> manifests: updater mount the directory, not the socket

- pkg/manifests/yaml/nfd/topologyupdater/daemonset.yaml
- pkg/manifests/yaml/rte/daemonset.yaml
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
Quoting kube docs:
```
when accessing the `/var/lib/kubelet/pod-resources/kubelet.sock` from DaemonSet
or any other app deployed as a container on the host, which is mounting socket as
a volume, it is a good practice to mount directory `/var/lib/kubelet/pod-resources/`
instead of the `/var/lib/kubelet/pod-resources/kubelet.sock`. This will ensure
that after kubelet restart, container will be able to re-connect to this socket.
Container mounts are managed by inode referencing the socket or directory,
depending on what was mounted. When kubelet restarts, socket is deleted
and a new socket is created, while directory stays untouched.
So the original inode for the socket become unusable. Inode to directory
will continue working.
```
> [manual][release-0.14] manifests: updater mount the directory, not the socket

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
Let's update to the latest LTS from the ancient 20.04, and also let's take the chance to pin the version explicitely rather than rely to floating tags.
> [manual][release-0.14] ghactions: pin images to ubuntu 22.04

- pkg/commands/root.go
- pkg/deployer/deployer.go
- pkg/deployer/sched/sched.go
- pkg/deployer/updaters/objects.go
- pkg/deployer/updaters/updaters.go
- pkg/deployer/wait/wait.go
- pkg/deployer/wait/wait_test.go
- pkg/manifests/api/api.go
- pkg/manifests/nfd/nfd.go
- pkg/manifests/rte/rte.go
- pkg/manifests/sched/sched.go
- pkg/objectwait/api/api.go
- pkg/objectwait/nfd/nfd.go
- pkg/objectwait/rte/rte.go
- pkg/objectwait/sched/sched.go
- pkg/objectwait/waitable.go
commandline UX improvement for waitable objects: enable to set base (global) values.
Since this code is used only in command flow (e.g. not really needed by library code), start isolating it in their own source code files, until a more comprehensive reorganization happens.
Fixes: #201
> wait: consolidate command line wait path

- README.md
- cmd/deployer/main.go
- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/images.go
- pkg/commands/remove.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/commands/setup.go
- pkg/commands/validate.go
- pkg/deploy/cluster.go
- pkg/deploy/types.go
- pkg/deployer/deployer.go
- test/e2e/e2e_test.go
- test/e2e/positive.go
code in `pkg/commands` should do orchestration and compose functionality exposed by other packages; instead, we gathered some helper/logic in there, which should be moved elsewhere. We start with the `deployOnCluster` and `deploy` functionality in general, moving this into a newly created small `deploy` package (we are running out good names).
This enables us to do quite some long-needed cleanup along the way.
Fixes: #138
> more logic removal from commands

- .golangci.yaml
- Makefile
- cmd/deployer/main.go
- pkg/commands/render.go
- pkg/commands/root.go
- pkg/deployer/updaters/objects.go
- pkg/flagcodec/flagcodec.go
- pkg/manifests/manifests.go
- pkg/objectupdate/nfd/nfd.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/sched/sched.go
- pkg/stringify/noderesourcetopology.go
Add new makefile target to run golangci-lint and to be used by developers.
Later (soonish) we will integrate golangci-lint in CI using the recommended GH action.
This PR also includes a batch of related fixes for the issues raised by the golangci-lint run.
> golangci-lint add developer config and related fixes

- pkg/deployer/api/api.go
- pkg/deployer/sched/sched.go
- pkg/deployer/updaters/updaters.go
- pkg/deployer/wait/crd.go
- pkg/objectwait/api/api.go
Add wait functions for CRD created/deleted.
Creating and deleting CRDs is expected to be fast, but not immediate. In CI envs, we can have flakes because CRDs are not deleted fast enough and the attempt to re-create thus fails, failing the test.
In all practical environments the operation should be so fast that the extra gets/wait time should
be negligible - and in general we do this steps
very rarely, in the order of 1-2 times per *cluster* lifespan.
Considering the cost is expected to be negligible and that the code is now more correct, we add and
use functions, which should also reduce e2e flakes.
> wait: add helpers for CRDs

- pkg/deployer/wait/crd.go
- pkg/deployer/wait/daemonset.go
- pkg/deployer/wait/deployment.go
- pkg/deployer/wait/wait.go
- pkg/kubeletconfig/configz.go
- pkg/manifests/schedparams.go
- pkg/objectupdate/sched/render.go
> cleanups: fix linter issues 20231026

- pkg/manifests/schedparams_test.go
- pkg/manifests/yaml/sched/configmap.yaml
- pkg/objectupdate/sched/render_test.go
v1beta2 config is deprectated and on its way to removal. For our goals, though, v1beta3 should be fully compatible and little more than a trivial rename (if at all). Let's start with the trivial rename.
> sched: manifests: v1beta2 -> v1beta3

- .github/workflows/e2e.yml
- Makefile
- test/e2e/e2e_test.go
- test/e2e/manifests.go
deploy using rendered manifests, and verify the deployment.
Fixes: #90
> e2e: add a lane to deploy and verify using rendered manifests

- pkg/flagcodec/flagcodec.go
- pkg/flagcodec/flagcodec_test.go
Add more docs and test coverage; most notably, clarify it is safe and supported to just call Delete() against nonexistent options. Much like `delete` on maps,
it will turn as no-operation silently and succesfully.
> chore: pkg: flagcodec: more test coverage and docs

- pkg/flagcodec/flagcodec.go
- pkg/flagcodec/flagcodec_test.go
Add more docs and test coverage; most notably, clarify it is safe and supported to just call Delete() against nonexistent options. Much like `delete` on maps,
it will turn as no-operation silently and succesfully.
> [release-0.18][manual] chore: pkg: flagcodec: more test coverage and docs

- test/e2e/manifests.go
- test/e2e/positive.go
- test/e2e/utils/pods/pods.go
The test
```
[PositiveFlow] Deployer execution with a running cluster without any components
when deployed with resource-topology-exporter as the updater [It] should verify
a test pod scheduled with the topology aware scheduler goes running
```
started to flake lately with the symptoms matching a timeout due to slow CI.
Relax the timeout and add more logs to (try to) deflake the issue.
> e2e: relax running timeout

- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
Add support to gather and set cache fine-tuning parameters:
ForeignPodsDetectMode and CacheResyncMethod, both exposed
in the `cache` subfield of the plugin parameters (at least
cacheResyncPeriodSeconds also belong there, but this is
another story for another day).
Also add validation support for the parameters.
> manifests: objectupdate: cache fine-tuning support

- RATIONALE.md
- README.md
inspired by https://github.com/tetratelabs/wazero/blob/main/RATIONALE.md
> docs: kickstart rationale doc

- pkg/flagcodec/flagcodec.go
- pkg/flagcodec/flagcodec_test.go
- pkg/manifests/yaml/sched/scheduler/deployment.yaml
- pkg/objectupdate/nfd/nfd.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/sched/sched.go
- pkg/objectupdate/sched/sched_test.go
> WIP: flagcodec: enable flag normalization

- cmd/deployer/main.go
- test/e2e/e2e_test.go
- vendor/k8s.io/klog/v2/klogr/README.md
- vendor/k8s.io/klog/v2/klogr/klogr.go
- vendor/modules.txt
Starting controller-runtime >= 0.15, which we use
mostly for client and type definitions, its logger needs to be initialized explicitly. Let's do so.
Fixes: https://github.com/k8stopologyawareschedwg/deployer/issues/247
> tree: e2e: initialize controller-runtime log

- pkg/assets/selinux/assets.go
- pkg/assets/selinux/assets_test.go
- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/assets/selinux/policy/ocp_v4.15.cil
add support for OCP 4.15 for the RTE selinux policy
remove deprecated constant in the package
> add support for RTE selinux policy compatible with OCP >= 4.15

- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/assets/selinux/policy/ocp_v4.15.cil
updates to selinux policies for OCP 4.14 and 4.15. Fix expected process context and minimize the permission list.
> [release-0.18][manual] selinux policy: refine process contexts

- pkg/assets/selinux/assets_test.go
- pkg/assets/selinux/policy/ocp_v4.14.cil
- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/commands/render.go
add more policy cleanups for recent OCPs, and add a command to easily inspect the proposed policy.
> selinux: more policy cleanups

- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
The scheduler plugin gained support for the external informer, necessary to overcome  mismatch between the scheduler and the ode views wrt the pods on nodes.
Expose support in the deployer libraries to change this setting.
> sched: support for informerMode option

- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
The scheduler plugin gained support for the external informer, necessary to overcome  mismatch between the scheduler and the ode views wrt the pods on nodes.
Expose support in the deployer libraries to change this setting.
> [release-0.18][manual] sched: support for informerMode option

- pkg/manifests/schedparams.go
- pkg/manifests/schedparams_test.go
- pkg/objectupdate/sched/render.go
- pkg/objectupdate/sched/render_test.go
- test/e2e/manifests.go
- test/e2e/positive.go
- test/e2e/utils/pods/pods.go
cumulative backport of PRs #250 and #270
> [release-0.17][manual] backport scheduler cache tunings enhancement

- README.md
- hack/kind-config-e2e-positive.yaml
- pkg/validator/kubeletconfig.go
- pkg/validator/kubeletconfig_test.go
GetAllocatableResponse's FG matured in recent kubes (around 1.27) so there's no point anymore in checking it.
> config: don't check or use FeatureGate

- README.md
- hack/kind-config-e2e-positive.yaml
- pkg/validator/kubeletconfig.go
- pkg/validator/kubeletconfig_test.go
GetAllocatableResponse's FG matured in recent kubes (around 1.27) so there's no point anymore in checking it.
> [release-0.18][manual] config: don't check or use FeatureGate

- pkg/assets/selinux/policy/ocp_v4.13.cil
the 4.13 policy used to be the odd one, but since
the platform fixed it previous quirks, time to align also our custom policy.
> [release-0.18][manual] selinux: align 4.13 policy

- pkg/assets/selinux/policy/ocp_v4.13.cil
the 4.13 policy used to be the odd one, but since
the platform fixed it previous quirks, time to align also our custom policy.
> [release-0.17][manual] selinux: align 4.13 policy

- pkg/assets/selinux/policy/ocp_v4.13.cil
the 4.13 policy used to be the odd one, but since
the platform fixed it previous quirks, time to align also our custom policy.
> [release-0.15][manual] selinux: align 4.13 policy

- pkg/assets/selinux/policy/ocp_v4.13.cil
the 4.13 policy used to be the odd one, but since
the platform fixed it previous quirks, time to align also our custom policy.
> [release-0.14][manual] selinux: align 4.13 policy

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
bump the golang toolchain version
bump the module version, to be able to use new language features
> golang: toolchain: bump to 1.21

- pkg/commands/deploy.go
- pkg/commands/remove.go
- pkg/commands/render.go
- pkg/deploy/cluster.go
We need to pass the data in all the flows,
not just on the render flow.
(cherry picked from commit ffdce3e646a53ff756482ca9943891554981c275)
> [release-0.19] commands: sched: pass through scoringStrategy config

- pkg/images/consts.go
bump to consume the dep bump in rte, which in turn fix topology discovery in recent(ish) kernels.
> deps: rte: bump to v0.18.1

- .github/workflows/e2e.yml
- test/e2e/e2e_test.go
- test/e2e/manifests.go
- test/e2e/negative.go
- test/e2e/positive.go
- test/e2e/utils/pods/logs.go
- test/e2e/utils/pods/pods.go
Add helpers to make it easier to understand the test failures.
> e2e: add facilities to improve troubleshooting

- .github/workflows/e2e.yml
- test/e2e/e2e_test.go
- test/e2e/manifests.go
- test/e2e/negative.go
- test/e2e/positive.go
- test/e2e/utils/pods/logs.go
- test/e2e/utils/pods/pods.go
Add helpers to make it easier to understand the test failures.
backport of #296
> [release-0.19] e2e: add facilities to improve troubleshooting

- pkg/manifests/sched/sched.go
- pkg/manifests/sched/sched_test.go
- pkg/objectupdate/rbac/rbac.go
- pkg/objectupdate/rbac/rbac_test.go
We want to minimize privilege for the leader election role, this requires setting the specific resource name in the role definition, to let the scheduler change only its own resource.
Add helper, with tests, to enable this.
> rbac: add helper to update role for leaderelection

- cmd/deployer/main.go
- pkg/clientutil/nodes/nodes.go
- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/remove.go
- pkg/commands/root.go
- pkg/deploy/cluster.go
- pkg/deployer/platform/detect/autoselection.go
- pkg/deployer/platform/detect/detect.go
add utilities to getch all the controlplane nodes, similarly to worker node which we support since forever.
We can use this code to autodetermine the replica size.
> add utilities and options to detect control plane

- cmd/deployer/main.go
- pkg/clientutil/nodes/nodes.go
- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/remove.go
- pkg/commands/root.go
- pkg/deploy/cluster.go
- pkg/deployer/platform/detect/autoselection.go
- pkg/deployer/platform/detect/detect.go
add utilities to getch all the controlplane nodes, similarly to worker node which we support since forever.
We can use this code to autodetermine the replica size.
> [release-0.20][manual add utilities and options to detect control plane 

- cmd/deployer/main.go
- pkg/clientutil/nodes/nodes.go
- pkg/commands/deploy.go
- pkg/commands/detect.go
- pkg/commands/remove.go
- pkg/commands/root.go
- pkg/deploy/cluster.go
- pkg/deployer/platform/detect/autoselection.go
- pkg/deployer/platform/detect/detect.go
add utilities to getch all the controlplane nodes, similarly to worker node which we support since forever.
We can use this code to autodetermine the replica size.
>  [release-0.20][manual add utilities and options to detect control plane 

- pkg/assets/selinux/consts.go
- pkg/commands/render.go
- pkg/deployer/updaters/objects.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/manifests/rte/rte.go
- pkg/manifests/rte/rte_test.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
- pkg/options/options.go
- test/e2e/e2e_test.go
- test/e2e/manifests.go
- test/e2e/negative.go
- test/e2e/positive.go
So far, we were using a custom SELinux policy to allow RTE access to PodResourceAPI socket.
The `container_device_plugin_t` label type is a built-in context, which allows communication with
`kubelet_t` context: https://github.com/containers/container-selinux/pull/178.
The PodResourceAPI socket is an object created by Kubelet so it inherents
the same process context, i.e. `kubelet_t`.
This PR is changing RTE container to use `container_device_plugin_t` and make the logic needed for creating the custom policy as optional and off by default.
> OCP: SELinux: make custom policy opt-in and off by default

- pkg/manifests/sched/sched.go
The topology-aware-scheduler-leader-elect `rolebinding` object is refer to topology-aware-scheduler-leader-elect `role` which is under a specific namespace given the configuration provided to the deploy command.
we should set the right namespace for the `rolebinding` to be the same as the `role` namespace.
> scheduler: set namespace for rolebinding

- pkg/commands/root.go
- pkg/manifests/manifests_test.go
Add the `UpdaterCustomSELinuxPolicy` flag so we could control
whether we want to install custom policy from the deployer directly.
This flag is off by default.
> deployer:flags: `UpdaterCustomSELinuxPolicy`

- pkg/deployer/platform/detect/detect.go
- pkg/deployer/platform/detect/detect_test.go
- pkg/deployer/platform/platform.go
- pkg/deployer/platform/platform_test.go
Added the capeability for the deployer to detect
whether the targeted OpenShift platform is of HyperShift flavor.
In future PR on NROP, we'll consume this change to allow the operator performs specific decision given the current platform.
> detect: add capability to detect HyperShift platform

- pkg/deployer/platform/detect/detect.go
- pkg/deployer/platform/detect/detect_test.go
- pkg/deployer/platform/platform.go
- pkg/deployer/platform/platform_test.go
Added the capability for the deployer to detect
whether the targeted OpenShift platform is of HyperShift flavor.
We're keeping the old \`PlatformFromLister\` for the sake of backward compatability.
> [release-0.20][manual] detect: add capability to detect HyperShift platform

- pkg/manifests/sched/sched.go
The topology-aware-scheduler-leader-elect `rolebinding` object is refer to topology-aware-scheduler-leader-elect `role` which is under a specific namespace given the configuration provided to the deploy command.
we should set the right namespace for the `rolebinding` to be the same as the `role` namespace.
> [release 0.20][manual] scheduler: set namespace for rolebinding

- pkg/assets/selinux/assets.go
- pkg/assets/selinux/assets_test.go
- pkg/assets/selinux/policy/ocp_v4.17.cil
- pkg/assets/selinux/policy/ocp_v4.18.cil
podresources API context has changed to kubelet_var_lib_t:
https://github.com/containers/container-selinux/pull/329
Adjust the custom policy to allow access to this new file context.
> selinux: allow access to kubelet_var_lib_t

- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/assets/selinux/policy/ocp_v4.17.cil
In future rhel/rhcos release podresourceAPI socket file's context might change to `kubelet_var_lib_t`.
To deal with this issue in advance we'll change RTE custom policy to support this new context as well.
> selinux: add kubelet_var_lib_t permissions

- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/assets/selinux/policy/ocp_v4.17.cil
In future rhel/rhcos release podresourceAPI socket file's context might change to `kubelet_var_lib_t`.
To deal with this issue in advance we'll change RTE custom policy to support this new context as well.
(cherry picked from commit 12718ed5c8ea8647588b28104c371a0096759663)
> [release-0.21][manual] selinux: add kubelet_var_lib_t permissions

- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
bump base images and actions versions
to fix up the warnings and be a bit more future proof.
> gh actions: bump versions

- pkg/images/consts.go
pulls the ghw fixes which in turn caused our lanes to fail
> [release-0.19] deps: consume latest RTE 0.14 image

- pkg/deployer/deployer.go
- pkg/deployer/platform/detect/autoselection.go
- pkg/deployer/platform/detect/detect.go
- pkg/deployer/platform/detect/types.go
- pkg/deployer/platform/env.go
instead of implicitely automatically create clients, add function variants which take clients in the form of an Environment struct.
> platform: detect: add functions which take clients

- pkg/assets/selinux/policy/ocp_v4.16.cil
- pkg/assets/selinux/policy/ocp_v4.17.cil
This reverts commit 12718ed5c8ea8647588b28104c371a0096759663.
This approach doesn't work since the key is not defined
> Revert "selinux: add kubelet_var_lib_t permissions"

- pkg/manifests/manifests.go
- pkg/manifests/rte/rte.go
- pkg/manifests/yaml/rte/securitycontextconstraintv2.yaml
add a new SecurityContextConstraints object, alongside the existing one, with all the recommended settings enabled and narrowed down privileges. Can be used with OpenShift >= 4.18.
> manifests: selinux: openshift add v2 SCC

- pkg/commands/root.go
- pkg/manifests/rte/rte.go
- pkg/options/options.go
further test prove https://github.com/k8stopologyawareschedwg/deployer/pull/346 was incomplete.
We had a subtle bug which prevented the SCC V2 to be reported in the output of `ToObjects()`.
Also missing was the required wiring to let users select the SCC version from the command line tool.
Unfortunately OpenShift/HyperShift features need to be tested offline because this project lacks CI for these environments, and this missteps may happen.
A future PR will introduce (more) test coverage to reduce the chances of further missteps
>  manifests: selinux: openshift add v2 SCC - fixes

- pkg/manifests/rte/rte.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
Since OCP 4.18, all workloads of platform namespaces (openshift-*) explicitly pin the SCCs they need.
https://docs.openshift.com/container-platform/4.17/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
https://github.com/openshift/origin/blob/master/pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
> SCC: Added annotation to daemonset pods template

- pkg/manifests/yaml/rte/daemonset.yaml
- pkg/objectupdate/find.go
- pkg/objectupdate/find_test.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
This is a continuation of the effort to make the embedded manifests minimal and move most mutations in the `objectupdate` subpackages.
We still want to have an embedded skeleton as basis, but moving the mutations in the `objectupdate` subpkgs is meant to better support objects reconciliation.
> objectupdate: rte: continue minimization of manifests

- pkg/manifests/rte/rte.go
- pkg/objectupdate/rte/rte.go
- pkg/objectupdate/rte/rte_test.go
Since OCP 4.18, all workloads of platform namespaces (openshift-*) explicitly pin the SCCs they need.
https://docs.openshift.com/container-platform/4.17/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth
https://github.com/openshift/origin/blob/master/pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Signed-off-by: Ronny Baturov <rbaturov@redhat.com>
(cherry picked from commit f9b9c9183ca90955add402fe4f60ec01c6f36553)
> [release-0.21][manual] SCC: Added annotation to daemonset pods template

- pkg/objectwait/rte/rte.go
This PR complements the work done in #348.
The sections added were missing, which subsequently prevented the SCC v2 from being deployed.
> rte: selinux: missing v2 SCC creation and deletion

- pkg/manifests/yaml/rte/daemonset.yaml
Till today, the priority class of RTEs is 0 which is the default which is the lowest priority possible and is the first one in danger of being evicted. The first consumer of the RTE functionality is the topology-aware secondary scheduler which has `system-node-critical` priority class. RTE having a lower priority class risks the performance of the scheduler. and if RTE pods are evicted the scheduler becomes unreliable and completely blocked.
Increase the priority class of RTEs to `system-node-critical` to lessen the possibility of the daemonset pods getting evicted. This is especially needed for compact cluster use cases where eviction is more frequent due to prioritizing system-critical workloads.
> rte: specify priority class

- pkg/manifests/yaml/rte/daemonset.yaml
Till today, the priority class of RTEs is 0 which is the default which is the lowest priority possible and is the first one in danger of being evicted. The first consumer of the RTE functionality is the topology-aware secondary scheduler which has `system-node-critical` priority class. RTE having a lower priority class risks the performance of the scheduler. and if RTE pods are evicted the scheduler becomes unreliable and completely blocked.
Increase the priority class of RTEs to `system-node-critical` to lessen the possibility of the daemonset pods getting evicted. This is especially needed for compact cluster use cases where eviction is more frequent due to prioritizing system-critical workloads.
(cherry picked from commit dbbdf395ca3709602d64a04f55309126ba4866e6)
> [release-0.22] rte: specify priority class

- .github/workflows/release.yml
patch versions don't need binaries, and, unless
rare cases which can manage manually for the time being, don't change manifests.
From the last few years, patch versions are usually needed to fix/backport golang packages, so we can save space and CI credits and just consume tags.
(cherry picked from commit b1c82e1d00f7e359d2ef56567536586a725af857)
> [release-0.22] github actions: build releases only for majors

- .github/workflows/release.yml
patch versions don't need binaries, and, unless
rare cases which can manage manually for the time being, don't change manifests.
From the last few years, patch versions are usually needed to fix/backport golang packages, so we can save space and CI credits and just consume tags.
(cherry picked from commit b1c82e1d00f7e359d2ef56567536586a725af857)
> [release-0.20] github actions: build releases only for majors

- pkg/manifests/yaml/rte/daemonset.yaml
Till today, the priority class of RTEs is 0 which is the default which is the lowest priority possible and is the first one in danger of being evicted. The first consumer of the RTE functionality is the topology-aware secondary scheduler which has `system-node-critical` priority class. RTE having a lower priority class risks the performance of the scheduler. and if RTE pods are evicted the scheduler becomes unreliable and completely blocked.
Increase the priority class of RTEs to `system-node-critical` to lessen the possibility of the daemonset pods getting evicted. This is especially needed for compact cluster use cases where eviction is more frequent due to prioritizing system-critical workloads.
(cherry picked from commit dbbdf395ca3709602d64a04f55309126ba4866e6)
> [release-0.21] rte: specify priority class

- pkg/manifests/yaml/rte/daemonset.yaml
Till today, the priority class of RTEs is 0 which is the default which is the lowest priority possible and is the first one in danger of being evicted. The first consumer of the RTE functionality is the topology-aware secondary scheduler which has `system-node-critical` priority class. RTE having a lower priority class risks the performance of the scheduler. and if RTE pods are evicted the scheduler becomes unreliable and completely blocked.
Increase the priority class of RTEs to `system-node-critical` to lessen the possibility of the daemonset pods getting evicted. This is especially needed for compact cluster use cases where eviction is more frequent due to prioritizing system-critical workloads.
(cherry picked from commit dbbdf395ca3709602d64a04f55309126ba4866e6)
> [release-0.19] rte: specify priority class
